name: Code Analysis

on: push

jobs:
  code_analysis:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - '3.12'

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Setup .venv
      - name: Setup Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction

      # Mypy
      - name: Mypy
        run: poetry run mypy backup_scrapbox

      # Pylint
      - name: Pylint
        run: poetry run pylint backup_scrapbox

      # Black
      - name: Black
        run: poetry run black --check backup_scrapbox

      # isort
      - name: isort
        run: poetry run isort --check backup_scrapbox
